# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	clap@4.6.0
	clap_builder@4.6.0
	clap_derive@4.6.0
	clap_lex@1.1.0
	colorchoice@1.0.5
	heck@0.5.0
	ipnet@2.12.0
	is_terminal_polyfill@1.70.2
	itoa@1.0.17
	memchr@2.8.0
	once_cell_polyfill@1.70.2
	proc-macro2@1.0.106
	quote@1.0.45
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	strsim@0.11.1
	syn@2.0.117
	unicode-ident@1.0.24
	utf8parse@0.2.2
	windows-link@0.2.1
	windows-sys@0.61.2
	zmij@1.0.21
"

inherit cargo systemd

DESCRIPTION="A minimalist, purely data-driven management tool for WireGuard 🩸"
HOMEPAGE="https://github.com/denisstrizhkin/nazuna"
SRC_URI="
	https://github.com/denisstrizhkin/nazuna/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

RUST_MIN_VER="1.85.0"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
IUSE="systemd"

src_install() {
	cargo_src_install

	if use systemd; then
		systemd_dounit systemd/nazuna.service
	else
		newinitd openrc/nazuna nazuna
	fi
}
